# Generated by Django 5.2.4 on 2025-08-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTNDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('decoded_payload', models.JSONField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('fcnt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ttndevice')),
            ],
        ),
    ]
